### ISSUE TITLE
Tests are failing under NodeJS v5.5.0

### ISSUE THREAD

**Issue by StephanMeijer** [cayasso/engine.io-rooms#1]
Running `v5.5.0` under `Arch Linux`.

Command: `make test`

Output:

```


  engine.io-rooms
    1) should have required methods


  0 passing (2s)
  1 failing

  1) engine.io-rooms should have required methods:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.




Makefile:4: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by StephanMeijer** [comment]
Server is listening on IPv6. According to IPv6, `::` is a correct host. According to engine.io-client, `::` is an invalid host. I will do a pull request as soon as possible to fix this issue.

**Comment by cayasso** [comment]
@StephanMeijer engine.io-rooms@0.2.0 is out with this fix.

Thanks again!
